

version: '3.8'
services:
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=DJANGO_PROJECT.settings
    volumes:
      - .:/app
    networks:
      my_networks:
        ipv4_address: 172.28.1.1

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      my_networks:
        ipv4_address: 172.28.1.2

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      environment:
        - DB_HOST=${REDIS_HOST}
        - DB_NAME=${REDIS_PORT}
      networks:
        my_networks:
          ipv4_address: 172.28.1.3

  celery:
    restart: always
    build:
      context: .
    command: celery -A DJANGO_PROJECT worker -l info
    volumes:
      - .:/app
    environment:
      - DB_HOST=${REDIS_HOST}
      - DB_NAME=${REDIS_PORT}
    networks:
      my_networks:
        ipv4_address: 172.28.1.4

networks:
    my_networks:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
